### PR TITLE
added bbgcid for iPhone9,2

### PR DESCRIPTION
**Pull request by 0x2400**

### CODE REVIEW

**Comment by tihmstar** [comment]
There is an issue requesting baseband ticket for iPhone9,2
either bbgcid is incorrect or there is a different issue in tsschecker.
could you send me a capture of a valid tss request via email? for example request it with idevicerestore or itunes and capture the request

**Comment by galaxy001** [comment]
I checked on my iPhone 7 Plus and find the same value:
`$ ideviceinfo -s
BasebandCertId: 2315222105`

**Comment by tihmstar** [comment]
I belive the issue is not the bbgcid, but a different value is wrong. To debug that i need a dump of a tssrequest, which does give me a valid ticket. You can getting one with `idevicerestore -t -d -l` in normal mode. 
However i'm not 100% sure that'll also request a baseband ticket. If that doesn't work, i need someone to restore his iPhone with -d parameter in idevicerestore and send me the full log (or just the good tss request)

**Comment by SConaway** [comment]
@tihmstar Bump?

**Comment by tihmstar** [comment]
Seems to work now as of version 261
```
tsschecker -l -d iPhone9,2 --no-baseband=2
Version: 3efa4ac03e52e8482fca0ee9f68479034e84a881 - 261
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[TSSC] selecting latest iOS: 12.1
[TSSC] got firmwareurl for iOS 12.1 build 16B92
[TSSC] opening Buildmanifest for iPhone9,2_12.1_16B92
[LFZP] downloading BuildManifest.plist from http://updates-http.cdn-apple.com/2018FallFCS/fullrestores/091-91067/9618539E-D4BE-11E8-B2F7-9E701074CB12/iPhone_5.5_P3_12.1_16B92_Restore.ipsw
100 [===================================================================================================>]
[TSSR] User specified to request only a Baseband ticket.
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
iOS 12.1 16B92 IS signed!

iOS 12.1 for device iPhone9,2 IS being signed!
```

**Pull request closed without merging**
